server {
    listen 8082 ssl;
    server_name k3s-8082-service.default.svc.cluster.local;
    # 証明書と秘密鍵のパスを指定
    ssl_certificate     /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;
    location /abc {
        proxy_pass http://k3s-8080-service.default.svc.cluster.local:8080/abc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /efg {
        proxy_pass http://k3s-8081-service.default.svc.cluster.local:8081/efg;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
