apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-2222-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-2222-app
  template:
    metadata:
      labels:
        app: k3s-2222-app
    spec:
      containers:
      - name: k3s-2222-app
        image: docker.io/library/k3s-2222:v1.0 # sudo k3s ctr images listで得たREF
        imagePullPolicy: Never
        ports:
        - containerPort: 8080  # ここでポート番号を指定
          protocol: TCP     # デフォルトはTCP
