- name: サービスの有効化と起動
  ansible.builtin.systemd:
    name: "{{ tasks_item.service_name }}"
    state: stopped
    enabled: yes
    daemon_reload: yes
  ignore_errors: True
  become: True

- name: サービスが正常に停止しているか確認
  ansible.builtin.command: systemctl status {{ tasks_item.service_name }}
  register: service_status
  changed_when: False
  ignore_errors: True
  become: True

- name: ステータスを表示
  ansible.builtin.debug:
    var: service_status.stdout_lines


